package com.minichoice.domain;

public enum ConstraintType {
    MAX_ASSIGNMENTS_PER_RESOURCE,
    MAX_ASSIGNMENTS_PER_CANDIDATE,
    MAX_TOTAL_ASSIGNMENTS,
    MIN_PRIORITY_THRESHOLD,
    MAX_TOTAL_COST,
    CANDIDATE_REQUIRES_RESOURCE_TYPE
}